[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.2"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hakata_perpetuals = "6wCkVSLvphXyQphT8xDemkx92caLJXcaFF9qjxxL2o8Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/anchor/*.ts"
